### ISSUE TITLE
Enable the use of custom filesystems

### ISSUE THREAD

**Issue by N247S** [expressjs/serve-index#101]
Currently serve-index uses the default node.js' `fs` library to querry their files. But it would be usefull if a custom fileSystem could be set instead.

This would enable this [SO issue](https://stackoverflow.com/questions/68787350/webpack-enable-file-listing-of-emited-files-without-write-to-disk-option) to be resolved for instance (either by a custom plugin, or actually implemented into the webpack-dev-server).

**Comment by N247S** [comment]
Would love to know if you can figure this out.

I tried several options to get this working but no luck so far.
I figured out that it is the initial (full) require sequence which makes it write to the disk. So I currently mock it as follows:

```javascript
const serveIndex = proxyRequire('serve-index',
{
  fs:
    {
      stat: function()
      {
        return devServer.middleware.context.fs.stat(...arguments);
      },
      readdir: function()
      {
        return devServer.middleware.context.fs.readdir(...arguments);
      },
      readFile: function()
      {
        return fs.readFile(...arguments); // don't override this, otherwise it cannot find the .html/.css files
      },
      readFileSync: function()
      {
        return fs.readFileSync(...arguments); // don't override this, otherwise it cannot find the .html/.css files
      }
    },
}
```

It doesn't really throw errors, but apparently the `stats` call on the MemoryFileSystem returns `undefined`, which throws errors further down the road (when `mtime` is queried).

**Comment by N247S** [comment]
I got it working by simply mocking the 2 values this project is using (`stats.mtime` and `stats.size`). It does a half `null` check, but unfortunately not on the values presense itself (It is something that might brake on very rare occasions, appart from this specific usecase). As far as I could find it is also not documented that those values have to be present as the example shown on the [Node.js File System Documentation](https://nodejs.org/api/fs.html#fs_class_fs_stats). The `birthtime` property is not supported on all filesystems for example.

So to be fully compatible with all the file-systems you might want to adjust the `null` checks. Simply change the `index.js` file at line 297 to (should be fully backwards compatible):

```javascript
// https://github.com/expressjs/serve-index/blob/d2922cd872f8038d4d4c60d936954c35200cfbad/index.js#L297
    var date = file.stat && file.stat.mtime && file.name !== '..' 
      ? file.stat.mtime.toLocaleDateString() + ' ' + file.stat.mtime.toLocaleTimeString()
      : '';
    var size = file.stat && file.stat.size && !isDir
      ? file.stat.size
      : '';
```


I could get the full 'mock' working with the following snippet
```javascript

const serveIndex = proxyquire('serve-index',
{
  fs:
    {
      stat: function()
      {
        return devServer.middleware.context.fs.stat(path, function(err, stat)
          {
            if (stat)
            {
              // mock properties used by 'serve-index'
              stat.mtime = new Date();
              stat.size = 0;
              cb(err, stat)
            }
            else cb(err, null);
          });
      },
      readdir: function()
      {
        return devServer.middleware.context.fs.readdir(...arguments);
      }
    },
});
```

So for your test, the full webpack.config.js file becomes:

```javascript
const path = require('path');
const isAbsoluteUrl = require('is-absolute-url')
const proxyquire = require('proxyquire');

module.exports = {
	mode: 'development',
	entry: './test.js',
	output:
	{
		path: path.resolve(__dirname, 'dist'),
		filename: 'foo.bundle.js',
	},
	devServer:
	{
		host: 'localhost',
		port: 3000,
		open: true,
		writeToDisk: false, // defaults to false
		serveIndex: false, // is needed because the contentBase routes are otherwise already resolved by an empty index (and the replacement will never be called
		onListening: function(devServer)
		{
			const serveIndex = proxyquire('serve-index',
			{
				fs:
				{
					stat: function()
					{
						return devServer.middleware.context.fs.stat(path, function(err, stat)
						{
							if (stat)
							{
								// mock properties used by 'serve-index'
								stat.mtime = new Date();
								stat.size = 0;
								cb(err, stat)
							}
							else cb(err, null);
						});
					},
					readdir: function()
					{
						return devServer.middleware.context.fs.readdir(...arguments);
					}
				},
			});

			// copied and modified from the function `setupServeIndexFeature()` from the `Server.js` file in the `webpack-dev-server` project
			const contentBase = devServer.options.contentBase;
			const contentBasePublicPath = devServer.options.contentBasePublicPath;
			const fs = devServer.middleware.context.fs;

			if (Array.isArray(contentBase))
			{
				contentBase.forEach((item) =>
				{
					devServer.app.use(contentBasePublicPath, (req, res, next) =>
					{
						// serve-index doesn't fallthrough non-get/head request to next middleware
						if (req.method !== 'GET' && req.method !== 'HEAD')
							return next();
						serveIndex(fs, item, { icons: true })(req, res, next); // assuming you can pass the FileSystem object into this function
					});
				});
			}
			else if (typeof contentBase !== 'number' && !isAbsoluteUrl(String(contentBase)))
			{
				devServer.app.use(contentBasePublicPath, (req, res, next) =>
				{
					// serve-index doesn't fallthrough non-get/head request to next middleware
					if (req.method !== 'GET' && req.method !== 'HEAD')
						return next();
					serveIndex(fs, contentBase, { icons: true })(req, res, next); // assuming you can pass the FileSystem object into this function
				});
			}
		}
	},
};
```


Hopefully this is enough for you to start thinking/working on a future improvement 😄.
For me this solves it temporarily, I might make this into a plugin, in which case I will revisit this (hopefully).

Thanks for your time, the fast replies and hinting towards the `proxyquire` library (had never heard from it before this).

**Comment by dougwilson** [comment]
> As far as I could find it is also not documented that those values have to be present as the example shown on the Node.js File System Documentation. The birthtime property is not supported on all filesystems for example.

Are you sure? It would be expected all those are these _unless_ the docs say otherwise. I looked though the Node.js source code and it does not seem possible those values could be missing. Can you point to the source code in Node.js where it could be possible? Are you sure you are not just thinking if values between different Node.js versions?

**Comment by dougwilson** [comment]
It seems Node.js even has a test that validates all the properties are there for all platforms: https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/test/parallel/test-fs-stat.js#L85

**Comment by dougwilson** [comment]
> The birthtime property is not supported on all filesystems for example.

The documentation states that Libuv emulates the birthtime by setting it to the change time when it's unsupported.

**Comment by dougwilson** [comment]
> So to be fully compatible with all the file-systems you might want to adjust the null checks.

I took a look and it seems that the goal of memjs is to provide an exact replica of the Node.js API. It would seem that this is a bug in memjs that we probably found. I cannot find anywhere in Node.js where these can be null. If you can provide an example, we can certainly patch it. As far as I can tell, this is simply a bug in the memjs emulation of the Node.js fs API.

**Comment by dougwilson** [comment]
Looking though `memfs` I cannot see how `stat` could be missing or missing any of the properties. I even did a simple stand-alone test:
```js
$ node -pe 'fs=require("memfs");fs.writeFileSync("/foo","bar");fs.statSync("/foo")'
Stats {
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 2,
  size: 3,
  blocks: 1,
  atime: 2021-08-30T07:32:51.466Z,
  mtime: 2021-08-30T07:32:51.467Z,
  ctime: 2021-08-30T07:32:51.466Z,
  birthtime: 2021-08-30T07:32:51.466Z,
  atimeMs: 1630308771466,
  mtimeMs: 1630308771467,
  ctimeMs: 1630308771466,
  birthtimeMs: 1630308771466,
  dev: 0,
  mode: 33206,
  nlink: 1
}
```

**Comment by N247S** [comment]
Well I didn't care to dig through source codes (and trusted the documentation). Apparently I was too quick to judge here 😄.

Keep in mind though that it is using the old `memory-fs` instead of the newer (propably patched) `memfs` library. This old dependency is something I cannot change, as it is used by the `webpack-dev-server` internally. (they also use an ancient `webpack-dev-middleware` version).

So in that case, this would be a patch of an ancient bug?

**Comment by N247S** [comment]
And it does seem to be missing something... 🤔 

https://github.com/webpack/memory-fs/blob/3daa18e010ac10b05a3ecaa6342406722a609109/lib/MemoryFileSystem.js#L72

**Comment by dougwilson** [comment]
Hm, IDK. But the idea here is that one would pass in a reference to replace the `fs`. So if what you are trying to provide is not the same as how Node.js `fs` works, that goes back to my very first question: we need to lay out what the entire API is that you think the argument to this module should be. If the idea is that it is "a replace for `fs`", then it would be expected to work just like Node.js  `fs` and thus would be a bug outside this module. If the idea is that there is a _different_ API that you want to pass in to this module, we need to get the full API listed out here so we can understand what this module is supposed to expect for the results under various conditions.

**Comment by dougwilson** [comment]
> Keep in mind though that it is using the old memory-fs instead of the newer (propably patched) memfs library. This old dependency is something I cannot change, as it is used by the webpack-dev-server internally. (they also use an ancient webpack-dev-middleware version).

I'm not sure I'm following. `webpack-dev-server` depends on `webpack-dev-server@5` (https://github.com/webpack/webpack-dev-server/blob/c846a4573cf77418b09abaf5db30b1d23aaa0297/package.json#L58) which in turn uses `memfs` (https://github.com/webpack/webpack-dev-middleware/blob/8810db8453b9b72a865e431a00e023753f6aa9fb/package.json#L45).

**Comment by N247S** [comment]
Well that is a new one. 4.0.0 is just recently out of beta. So I just did a clean install which allowed it to update to the latest version. Lets see what happens now (need to cleanup the breaking changes first)

**Comment by N247S** [comment]
Oke, new results. With the webpack-dev-server 4.0.0 it is working without mocking `file.stats` properties.
webpack.config.js file:

```javascript
const path = require('path');
const proxyquire = require('proxyquire');

module.exports = {
	mode: 'development',
	entry: './test.js',
	output:
	{
		path: path.resolve(__dirname, 'dist'),
		filename: 'foo.bundle.js',
	},
	devServer:
	{
		host: 'localhost',
		port: 3000,
		open: true,
		devMiddleware:
		{
			index: false, // is needed because the contentBase routes are otherwise already resolved by an empty index (and the replacement will never be called)
		},
		onListening: function(devServer)
		{
			const serveIndex = proxyquire('serve-index',
			{
				fs:
				{
					stat: function()
					{
						return devServer.middleware.context.outputFileSystem.stat(...arguments);
					},
					readdir: function()
					{
						return devServer.middleware.context.outputFileSystem.readdir(...arguments);
					},
				},
			});

			// copied and modified from the function `setupStaticServeIndexFeature()` from the `Server.js` file in the `webpack-dev-server` project
			devServer.app.use(path.resolve(__dirname, 'dist'), (req, res, next) =>
			{
				// serve-index doesn't fallthrough non-get/head request to next middleware
				if (req.method !== "GET" && req.method !== "HEAD")
					return next();
				serveIndex(path.resolve(__dirname, 'dist'), { icons: true })(req, res, next);
			});
		}
	},
};
```

They made however a big change in that the index is actually used for 'static' sources only, so this would be a 'new feature' rather than a 'bug' or something (amongst those lines). So I guese supporting a custom `fs` argument will suffice after all?
