### ISSUE TITLE
Add link to root directory

### ISSUE THREAD

**Issue by whitneyit** [expressjs/serve-index#23]
Currently, the [`htmlPath`](https://github.com/expressjs/serve-index/blob/5b2ff74554f1c93aa8e8720a79d8a182bb7fc231/index.js#L229-L235) function correctly returns a series of links to child directories of a resource, but it does not provide a link to the "root" folder.

For example. Given you have navigated to `"/foo/bar"`, the following html is created:

``` html
<h1>
    /
    <a href="/foo">foo</a>
    /
    <a href="/bar">bar</a>
</h1>
```

Would you guys be open to a PR that would simply prepend the following `"<a href="/">~</a>"` to what is being returned by `htmlPath` so as the generated html would look like this:

``` html
<h1>
    <a href="/">~</a>
    /
    <a href="/foo">foo</a>
    /
    <a href="/foo/bar">bar</a>
</h1>
```

This way there is a quick link back to the root folder of the directory that is being served.

**Comment by dougwilson** [comment]
Published as 1.6.0
