### ISSUE TITLE
links to files don't work when using a changed base url with app.use.

### ISSUE THREAD

**Issue by andineck** [expressjs/serve-index#32]
when listing the files/directories with a custom base url using app.use, navigating the directories works, but the links to the files are broken.:

```js
app.use(express.static(path.join(__dirname, 'public')));
app.use('/file-viewer', serveIndex('public'));
```

Links to the files obviously work when using without 'mount path'.
```js
app.use(serveIndex('public'));
```

is there a way (option) for this use case?

**Comment by dougwilson** [comment]
It should actually be working right now, hm... Can you paste what the `<a` links look like in the HTML when you use a mount point and what version of this library you're using is?

**Comment by dougwilson** [comment]
Oh, I see now; they're not broken: your `express.static` has to be mounted to the same mount point. i.e.:
```js
app.use('/file-viewer', express.static(path.join(__dirname, 'public')));
app.use('/file-viewer', serveIndex('public'));
```

**Comment by andineck** [comment]
Ah, yes, sure. makes sense, that will work. thank you!
