### ISSUE TITLE
Search only works in Safari (iOS/desktop)

### ISSUE THREAD

**Issue by thenoelforte** [expressjs/serve-index#34]
I've tried implementing this on a production server, and noticed that the search highlights only work in Safari both on Mac and iPhone. Chrome and Firefox seem to be the odd ones out here.

**Comment by dougwilson** [comment]
I'll try to check it out, but in the meantime PRs welcome :)

**Comment by thenoelforte** [comment]
CloudFlare's rocket loader was breaking the script. For some reason whatever they did to it it caused Chrome and FIrefox to not like it. Thanks again for the prompt response.

**Comment by dougwilson** [comment]
Ah, very interesting. Good to know, though!
