### ISSUE TITLE
Enhancement Request - open files in new tab/window

### ISSUE THREAD

**Issue by jewkesy** [expressjs/serve-index#36]
Could you add an option that will allow files to open in new tab by adding target='_blank' to the file anchors?

Even better, if you could allow an array of file extensions as an option which would compare and apply the target attribute if matched?

Thanks

**Comment by dougwilson** [comment]
Are you not able to achieve this by using the `template` option (https://github.com/expressjs/serve-index#template) given a function?

**Comment by jewkesy** [comment]
Ah yes of course.  Thanks
