### ISSUE TITLE
files not downloading on click.

### ISSUE THREAD

**Issue by Abhivendra** [expressjs/serve-index#43]
How to make files to download on clicking them?

**Comment by dougwilson** [comment]
Hi! This module simply provides a listing of the files, and that question is really regarding the module you are using to serve up the files themselves. What you need to do is add the HTTP header `Content-Disposition: attachment` to your file responses. If you are using the `serve-static` module in conjunction, you can find an example of how to do this on that module's readme:

https://github.com/expressjs/serve-static/#serve-all-files-as-downloads

I hope this helps!

**Comment by Abhivendra** [comment]
Thanx , but i have coded it for myself :)

**Comment by dimmduh** [comment]
> Thanx , but i have coded it for myself :)

Can you provide example?
