### ISSUE TITLE
search is case sensitive , is that a bug or feature?

### ISSUE THREAD

**Issue by Abhivendra** [expressjs/serve-index#45]
<img width="1215" alt="screen shot 2016-01-23 at 5 29 20 am" src="https://cloud.githubusercontent.com/assets/8620274/12526331/7733d990-c192-11e5-9dbe-4943ef9dc199.png">

**Comment by dougwilson** [comment]
It's not really a bug, more like it was designed that way. I agree it should be case-insensitive, since that makes sense for the traditional search. A PR #38 already does that, I just need to get it merged.

**Comment by dougwilson** [comment]
Hi @Abhivendra, the pull request has been merged into `master` now. Sorry it took so long to merge, I was just waiting for a window to bump the minor version number, since I felt like this was an enhancement. It has been merged and will be release soon, as part of 1.8.0
