### ISSUE TITLE
Download/Save the file

### ISSUE THREAD

**Issue by t3m** [expressjs/serve-index#52]
Hello,

Thanks for the awesome code. Using the code below, I can get the listing of the the filesystem but can't download/save as. Is there a way I can enable this? Thanks for sharing.
```js
var express    = require('express')
var serveIndex = require('serve-index')
var app = express()
app.use('/ftp', serveIndex('public/ftp', {'icons': true}))
app.listen()
```
Tom,

**Comment by dougwilson** [comment]
You will need to combine this module with some module that serves up the files themselves, like `serve-static` or the built-in `express.static` from Express. If you use `serve-static`, here is an example for serving files as downloads: https://github.com/expressjs/serve-static#serve-all-files-as-downloads

I hope that helps!

**Comment by Moxmi** [comment]
If i use express, what can i do for serving files as downloads?
