### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by lv7777** [expressjs/serve-index#55]
when I use serve-index in certain condition ,I get error.
___
console
```
Error: EPERM: operation not permitted, stat 'C:\System Volume Information'
    at Error (native)
```
___
source

```
var express=require("express");
var serveIndex = require('serve-index');

var app=express();

app.use(serveIndex("/",{hidden:true}));
```
I changed `serveIndex("/*",{hidden:true})`, the error was not showed, but I get `Cannot GET / ` error.

**Comment by dougwilson** [comment]
What directory are you actually trying to show the listing of? Are you intending to show `C:\`?

**Comment by lv7777** [comment]
I want listing project root directory.(C:\Users\user\Desktop\getserver)
maybe the code was try listing absolute path(`C:\`)

**Comment by dougwilson** [comment]
In that case, you should provide the path `C:\Users\user\Desktop\getserver` to this module, not `/` (which Node.js interprets as the root path of the CWD, `C:\` in your case). Example:
```js
var express=require("express");
var serveIndex = require('serve-index');

var app=express();

app.use(serveIndex("C:\\Users\\user\\Desktop\\getserver",{hidden:true}));
```
