### ISSUE TITLE
Public file not found when file compiled after babel and webpack

### ISSUE THREAD

**Issue by simonmysun** [expressjs/serve-index#58]
```javascript
import express from 'express';
import serveIndex from 'serve-index';

export default {
  start(options, callback) {
    const app = express();
    app.use(express.static(options.targetPath));
    app.use('/', serveIndex(options.targetPath, {
      icons: true,
    }));
    app.listen(options.port, () => {
      console.log(`Listening on port ${options.port}!`);
      callback();
    });
  },
};
```

This file will be compiled by Babeljs with target 'node' and preset 'es2015-node', then using webpack to bundle with other files. Running the output file the server started successfully. The static files are very well served. But the functionality of serving the directory fails. Both browser and console shows 
```

Error: ENOENT: no such file or directory, open '/path/to/option.targetPath/public/style.css'
```

Any one knows why? Thank you in advance!

**Comment by dougwilson** [comment]
I have never personally used Babel or webpack, so don't know off-hand what you're running into. It's weird that the open error you're showing is on a file, though. Does that error have a stack trace at all? Or, who do I use babel / webpack to replicate what you are seeing?

**Comment by simonmysun** [comment]
Hi, 

Thank you for your attention. Unfortunately the errors do not include any other information. I uploaded [a minimal version of this bug][1]. You may clone it or simply download and run [the one compiled on my computer][2]. I hope you can replicate what I see. 

There some build scripts inside that may help or disturb your testing: 
* `npm run build`: compile the code with webpack
* `npm run serve`: run the compiled express server
* `npm run dev`: compile and run and auto restart when source code is modified

BTW, webpack on my computer reported something else: 
```
    WARNING in ./~/express/lib/view.js
    Critical dependencies:
    78:29-56 the request of a dependency is an expression
     @ ./~/express/lib/view.js 78:29-56
    
    ERROR in ./~/batch/index.js
    Module not found: Error: Cannot resolve module 'emitter' in /home/mysun/tmp/express-index/node_modules/batch
     @ ./~/batch/index.js 8:16-34
```

The error can be prevented by `npm install emitter` however `emitter` is not anywhere in my code and whether I installed it or not the problem in this issue always happen. 

And my environment:
```
[root@MYS-Y3P tmp-for-test]# uname -a
Linux MYS-Y3P 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
[root@MYS-Y3P tmp-for-test]# node --version
v7.2.1
[root@MYS-Y3P tmp-for-test]# npm --version
4.0.3
```

[1]: https://github.com/simonmysun/tmp-for-test
[2]: https://github.com/simonmysun/tmp-for-test/blob/master/dist/server.js

**Comment by dougwilson** [comment]
Sorry I didn't get back right away. The issue is that the bundle does not correctly handle the fact that the `public/` directory of this module needs to be accessible to read the assets like the stylesheet. I can see two possible options:

1. Make a PR or something to WebPack to handle modules that need to read their corresponding assets.
2. Pass the `template` and `stylesheet` options to a path that points to the paths for the stylesheet and template assets.
