### ISSUE TITLE
Allow use of tables

### ISSUE THREAD

**Issue by wolfy1339** [expressjs/serve-index#60]
I want to use this module with Bootstrap 3.3.7 and use tables but in the source code it is harcoded to use a un-ordered list (ul). If this could be customizable that would be awesome

**Comment by dougwilson** [comment]
Does using a function for the template option not allow you to customize that?

**Comment by greggman** [comment]
I posted [an example of using a template over here](https://github.com/expressjs/serve-index/issues/50)
