### ISSUE TITLE
POST requests are rejected with 405

### ISSUE THREAD

**Issue by ledlamp** [expressjs/serve-index#70]
If serve-index gets a POST request (or any request other than GET, HEAD, & OPTIONS) it responds to it with a 405 Method Not Allowed. It should call next() so the next middleware can handle the request.

I know I can handle the POST request before it gets to the serve-index middleware but that is not feasible with our setup right now.

**Comment by dougwilson** [comment]
Ah, yes, indeed. I think that is what PR #61 is trying to fix, but it is very incomplete and the docs in it don't correctly describe what the option is doing. Do you want to take up the torch on that PR?

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by roman-la** [comment]
@ledlamp take a look at this https://stackoverflow.com/questions/34494634/http-post-express-server-returns-405-error-if-it-enables-serve-index/64137350#64137350

**Comment by ledlamp** [comment]
> @ledlamp take a look at this https://stackoverflow.com/questions/34494634/http-post-express-server-returns-405-error-if-it-enables-serve-index/64137350#64137350

oh hmm that's a good idea but the thing I was working on is loong gone now 😆

I think this issue should be left open though; just because nobody cares to fix it right now doesn't mean it's _not_ an issue 🙄
