### ISSUE TITLE
add .npmignore

### ISSUE THREAD

**Issue by ConnorSkees** [expressjs/serve-index#92]
There is significant bloat that could be fixed by adding an `.npmignore` file

To this end, what is the purpose of including 90 icons in the `public/icons` directory? I can't really figure out why they're included, and they're causing a lot of bloat (also, it's hard for me to search for `*.png` because they clutter the results)

**Comment by dougwilson** [comment]
The icons are part of the displayed HTML page.

**Comment by ConnorSkees** [comment]
Would it be possible to just ignore the markdown files and license in that case?

**Comment by dougwilson** [comment]
No

**Comment by dougwilson** [comment]
https://docs.npmjs.com/misc/developers

> The following paths and files are never ignored, so adding them to .npmignore is pointless:

> package.json
> README (and its variants)
> CHANGELOG (and its variants)
> LICENSE / LICENCE
