### ISSUE TITLE
svg icon 

### ISSUE THREAD

**Issue by AverTry** [expressjs/serve-index#99]
The SVG icon fails to show, probably because it contains a plus+ in the header and the class conversion fails to add anything. 

My workaround was to delete the image/svg+xml and simply add a .svg extension for it to lookup.

Could you fix or amend, so I don't have to hack your code, or fork? Thanks.

**Comment by dougwilson** [comment]
Hi @AverTry thank you for the report. I am able to reproduce the issue. I have a fix here for it that I will get committed here shortly 🎉
